# Generated by Django 4.2.7 on 2023-11-25 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoy', models.CharField(choices=[('math', 'M'), ('physics', 'P'), ('chemist', 'CH'), ('lecture', 'L')], max_length=50)),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('definitoin', models.TextField(blank=True)),
                ('situation', models.BooleanField(default=False)),
                ('mentor_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mentor.mentor')),
                ('student_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='student.student')),
            ],
        ),
    ]
