# Generated by Django 4.2.7 on 2023-11-26 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='categoy',
            new_name='category',
        ),
    ]
