# Generated by Django 4.2.7 on 2023-11-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='birth_date',
            new_name='birthday',
        ),
    ]
